import "./globals.css";
import { Montserrat } from "next/font/google";
import OidcProviderWrapper from "@lib/serviceCognito";
const fontMont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "QrCard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <OidcProviderWrapper>
        <body className={`${fontMont.className}`}>
          {children}
        </body>
      </OidcProviderWrapper>
    </html>
  );
}
